### ISSUE TITLE
Add HF Accelerate multi-node backend for Bloom 176B

### ISSUE THREAD

**Issue by ccmaymay** [hltcoe/sandle#47]
Multi-node usage of accelerate seems possible, just not very well documented:
* https://huggingface.co/docs/accelerate/basic_tutorials/launch
* https://github.com/huggingface/accelerate/issues/617
* https://github.com/huggingface/accelerate/issues/609
* https://huggingface.co/docs/accelerate/usage_guides/big_modeling
* https://huggingface.co/docs/accelerate/package_reference/big_modeling

**Comment by rekriz11** [comment]
I missed the last issue, but yes I know João Sedoc was also trying to figure out multi-node inference for OPT, so it may be worth reaching out to him to ask if he’s made progress. 

My overall impression was that it’s too slow to be usable, but if you’ve seen otherwise we can try it.

**Comment by ccmaymay** [comment]
Thanks!  That's good to know

**Comment by ccmaymay** [comment]
@rekriz11 do you happen to have any links to discussions/reports/etc. concerning that finding?  I'm curious about the details, if you have them!

**Comment by rekriz11** [comment]
João's response to me today:
"Yeah we got it running, but it was super slow."

He also sent me this tweet though, it seems like there may have been a breakthrough running on a single cluster using bnb-int8 for all hugging face models up to 175B!
https://twitter.com/tim_dettmers/status/1557343499225219072

**Comment by rekriz11** [comment]
Just an fyi, I have 175B sitting on the COE grid at /exp/rkriz/models/OPT/175b/.

**Comment by ccmaymay** [comment]
The docs mostly talk about training.  I thought that maybe I could use the same code for inference, but now I'm starting to question that.  Maybe distributed training means keeping a model fully loaded on different nodes and sending different batches of data to each node?

My last attempts produced this error after consuming all available memory:

```
19:05:32 cmay@brtx606 sandle (47-accelerate-bloom-176b) $ docker-compose run -p 17223:17223 --no-deps backend-hf --multi_gpu --machine_r
ank 0 --num_machines 5 --main_process_ip 172.23.93.106 --main_process_port 17223 run.py
WARN[0000] The "SENTRY_DSN" variable is not set. Defaulting to a blank string. 
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `8`
        `--mixed_precision` was set to a value of `'no'`
        `--num_cpu_threads_per_process` was set to `24` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/opt/sandle/run.py", line 43, in <module>
    main()
  File "/opt/sandle/run.py", line 29, in main
    output_token_ids = model.generate(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/generation_utils.py", line 1326, in generate
    return self.sample(
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/generation_utils.py", line 1944, in sample
    outputs = self(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 148, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py", line 828, in forward
    transformer_outputs = self.transformer(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py", line 715, in forward
    outputs = block(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 148, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py", line 416, in forward
    attn_outputs = self.self_attention(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 148, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py", line 277, in forward
    fused_qkv = self.query_key_value(hidden_states)  # [batch_size, seq_length, 3 x hidden_size]
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 148, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25) of binary: /opt/anaconda3/bin/python
```

I tried this with up to 5 unused BRTX nodes, which makes up 960 GB total GPU memory.  That should be way more than Bloom needs, extrapolating from the small models.

At the same time, the internet suggests one possible explanation for this error is that we're out of memory.  And monitoring GPU memory usage on [my nifty new dashboard](http://brtx-status.s3-website-us-east-1.amazonaws.com), we did somehow use up all 960 GB, and it was allocated in parallel (all five nodes' GPU memory was filled simultaneously, starting with GPU 0 on each node and ending at GPU 7).

So this part of accelerate isn't designed for inference and/or I'm using it wrong.  Unfortunately, there doesn't seem to be a whole lot of documentation for it in the first place.
