### ISSUE TITLE
Optionally use 8-bit inference with bits-and-bytes algorithm

### ISSUE THREAD

**Issue by ccmaymay** [hltcoe/sandle#52]
https://twitter.com/tim_dettmers/status/1557343499225219072

**Comment by ccmaymay** [comment]
@rekriz11 have you used the bnb-int8 code yet yourself?  Just extrapolating from the memory usage on OPT 66b, I'm guessing (but will check and make sure when things are back up and running) that 8 x 24 GB is not enough room for the full-size OPT/Bloom at 175b parameters.  Have you tried it/do you know?

**Comment by rekriz11** [comment]
I have not tried yet, I’ve been mostly trying variations of prompts with the smaller versions. From the tweet it seems like we should be able to?

Also the COE grid does have 8x32GB clusters, I know we’re looking to put this on BRTX though.

**Comment by ccmaymay** [comment]
Suspect this error arises from insufficient GPU memory:

```
sandle-backend-hf-1      | [2022-08-12 18:22:45,371] [ERROR] [waitress] Exception while serving /v1/completions
sandle-backend-hf-1      | Traceback (most recent call last):
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/waitress/channel.py", line 428, in service
sandle-backend-hf-1      |     task.service()
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/waitress/task.py", line 168, in service
sandle-backend-hf-1      |     self.execute()
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/waitress/task.py", line 456, in execute
sandle-backend-hf-1      |     for chunk in app_iter:
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/sentry_sdk/integrations/wsgi.py", line 269, in __iter__
sandle-backend-hf-1      |     reraise(*_capture_exception(self._hub))
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
sandle-backend-hf-1      |     raise value
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/sentry_sdk/integrations/wsgi.py", line 265, in __iter__
sandle-backend-hf-1      |     chunk = next(iterator)
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/werkzeug/wsgi.py", line 500, in __next__
sandle-backend-hf-1      |     return self._next()
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
sandle-backend-hf-1      |     for item in iterable:
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 408, in <genexpr>
sandle-backend-hf-1      |     (f'data: {event_data}\n\n' for event_data in chain(
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 409, in <genexpr>
sandle-backend-hf-1      |     (
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 164, in <genexpr>
sandle-backend-hf-1      |     return (
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 166, in <genexpr>
sandle-backend-hf-1      |     for c in (
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 183, in _stream_complete_single
sandle-backend-hf-1      |     (tokenizer, model) = self.get_tokenizer_and_model(model_id)
sandle-backend-hf-1      |   File "/opt/sandle/serve-backend-hf.py", line 112, in get_tokenizer_and_model
sandle-backend-hf-1      |     model = AutoModelForCausalLM.from_pretrained(
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
sandle-backend-hf-1      |     return model_class.from_pretrained(
sandle-backend-hf-1      |   File "/opt/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2182, in from_pretrained
sandle-backend-hf-1      |     raise ValueError("8-bit operations on `bitsandbytes` are not supported under CPU!")
sandle-backend-hf-1      | ValueError: 8-bit operations on `bitsandbytes` are not supported under CPU!
```

**Comment by ccmaymay** [comment]
I don't think this will work on BRTX.  I finally got it loaded on an 8 x 32 GB Tesla V100-SXM2(...) node on the COE grid and it used a total of 200,671 MiB just for the model (not including extra space for inference).  For comparison, the BRTX nodes have 8 x 24 GB Quadro RTX 6000, for a total of 193,760 MiB. @rekriz11 @nweir127

Of course, once I got the model loaded, it crashed anyway because these GPUs aren't new enough 😂

```
=============================================
ERROR: Your GPU does not support Int8 Matmul!
=============================================

python: /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu:379: int igemmlt(cublasLtHandle_t, int, int, int, const int8_t*, const int8_t*, void*, float*, int, int, int) [with int FORMATB = 3; int DTYPE_OUT = 32; int SCALE_ROWS = 0; cublasLtHandle_t = cublasLtContext*; int8_t = signed char]: Assertion `false' failed.
Aborted (core dumped)
```

**Comment by nweir127** [comment]
If it is helpful, I did not find that the bitsandbytes approach sped up any OPT models substantially nor used less space, but I did not look too far under the hood.
